apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: http-ds
spec: {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: http
  name: http
  namespace: http-ds
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: http
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - image: ghcr.io/micalgenus/test-http-container:1.3.1
          imagePullPolicy: IfNotPresent
          name: http
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
              hostPort: 8088
          env:
            - name: POD_NAME
              valueFrom:
                 fieldRef:
                   fieldPath: metadata.name
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 3
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: http-ds
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31080
  selector:
    app: http
  sessionAffinity: None
  type: NodePort

