apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    install.operator.istio.io/owning-resource: controlplane
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Base
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.16.1
    release: istio
  name: istiooperators.install.istio.io
spec:
  conversion:
    strategy: None
  group: install.istio.io
  names:
    kind: IstioOperator
    listKind: IstioOperatorList
    plural: istiooperators
    shortNames:
      - iop
      - io
    singular: istiooperator
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Istio control plane revision
          jsonPath: .spec.revision
          name: Revision
          type: string
        - description: IOP current state
          jsonPath: .status.status
          name: Status
          type: string
        - description:
            "CreationTimestamp is a timestamp representing the server time
            when this object was created. It is not guaranteed to be set in happens-before
            order across separate operations. Clients may not set this value. It is represented
            in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
            lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: istio-operator
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: istio-operator
    app.kubernetes.io/managed-by: Helm
    istio.io/rev: default
    name: istio-operator
    operator.istio.io/component: IstioOperator
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.12.0
  name: istio-operator
  namespace: istio-operator
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-metrics
      port: 8383
      protocol: TCP
      targetPort: 8383
  selector:
    name: istio-operator
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: istio-operator
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: istio-operator
    app.kubernetes.io/managed-by: Helm
    istio.io/rev: default
    operator.istio.io/component: IstioOperator
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.12.0
  name: istio-operator
  namespace: istio-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: istio-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      containers:
        - command:
            - operator
            - server
          env:
            - name: WATCH_NAMESPACE
              value: istio-system
            - name: LEADER_ELECTION_NAMESPACE
              value: istio-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: istio-operator
            - name: WAIT_FOR_RESOURCES_TIMEOUT
              value: 300s
            - name: REVISION
          image: 'docker.io/istio/operator:1.16.1'
          imagePullPolicy: IfNotPresent
          name: istio-operator
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1337
            runAsNonRoot: true
            runAsUser: 1337
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: istio-operator
      serviceAccountName: istio-operator
      terminationGracePeriodSeconds: 30
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: controlplane
  namespace: istio-system
spec:
  components:
    ingressGateways:
      - enabled: false
        name: istio-ingressgateway
    pilot:
      spec:
        resources:
          requests: {}
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        EXIT_ON_ZERO_ACTIVE_CONNECTIONS: 'true'
  profile: default
  values:
    global:
      proxy:
        holdApplicationUntilProxyStarts: true
        includeIPRanges: 10.0.0.0/8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: istio-operator
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    istio.io/rev: default
    operator.istio.io/component: IstioOperator
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.12.0
  name: istio-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-operator
subjects:
  - kind: ServiceAccount
    name: istio-operator
    namespace: istio-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: istio-operator
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    istio.io/rev: default
    operator.istio.io/component: IstioOperator
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.12.0
  name: istio-operator
rules:
  - apiGroups:
      - authentication.istio.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - config.istio.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - install.istio.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - networking.istio.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - security.istio.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions.apiextensions.k8s.io
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - apps
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/finalizers
      - replicasets
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - "*"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - roles
      - rolebindings
    verbs:
      - "*"
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - events
      - namespaces
      - pods
      - pods/proxy
      - pods/portforward
      - persistentvolumeclaims
      - secrets
      - services
      - serviceaccounts
    verbs:
      - "*"
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-system
  name: istio-system
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-operator
  name: istio-operator
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: istio-operator
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    istio.io/rev: default
    operator.istio.io/component: IstioOperator
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.12.0
  name: istio-operator
  namespace: istio-operator
