apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
  name: nodelocaldns
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: nodelocaldns
  template:
    metadata:
      annotations:
        prometheus.io/port: "9253"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        k8s-app: nodelocaldns
    spec:
      containers:
        - args:
            - -localip
            - 169.254.25.10
            - -conf
            - /etc/coredns/Corefile
            - -upstreamsvc
            - coredns
          image: k8s.gcr.io/dns/k8s-dns-node-cache:1.21.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              host: 169.254.25.10
              path: /health
              port: 9254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: node-cache
          ports:
            - containerPort: 53
              hostPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              hostPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 9253
              hostPort: 9253
              name: metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              host: 169.254.25.10
              path: /health
              port: 9254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/coredns
              name: config-volume
            - mountPath: /run/xtables.lock
              name: xtables-lock
      dnsPolicy: Default
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nodelocaldns
      serviceAccountName: nodelocaldns
      terminationGracePeriodSeconds: 0
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: Corefile
                path: Corefile
            name: nodelocaldns
          name: config-volume
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 20%
    type: RollingUpdate

